### ISSUE TITLE
ModuleNotFoundError: No module named 'pdfminer.psexceptions'

### ISSUE THREAD

**Issue by SecurityLover** [tonykipkemboi/ollama_pdf_rag#39]
I encountered this issue, help to fix it.

Traceback:

File "/home/user/Documents/ollama_pdf_rag/o_p_r/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "/home/user/Documents/ollama_pdf_rag/o_p_r/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "/home/user/Documents/ollama_pdf_rag/src/app/main.py", line 381, in <module>
    main()
File "/home/user/Documents/ollama_pdf_rag/src/app/main.py", line 276, in main
    data = loader.load()
           ^^^^^^^^^^^^^
File "/home/user/Documents/ollama_pdf_rag/o_p_r/lib/python3.12/site-packages/langchain_core/document_loaders/base.py", line 31, in load
    return list(self.lazy_load())
           ^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/Documents/ollama_pdf_rag/o_p_r/lib/python3.12/site-packages/langchain_community/document_loaders/unstructured.py", line 107, in lazy_load
    elements = self._get_elements()
               ^^^^^^^^^^^^^^^^^^^^
File "/home/user/Documents/ollama_pdf_rag/o_p_r/lib/python3.12/site-packages/langchain_community/document_loaders/pdf.py", line 72, in _get_elements
    from unstructured.partition.pdf import partition_pdf
File "/home/user/Documents/ollama_pdf_rag/o_p_r/lib/python3.12/site-packages/unstructured/partition/pdf.py", line 72, in <module>
    from unstructured.partition.pdf_image.pdfminer_processing import (
File "/home/user/Documents/ollama_pdf_rag/o_p_r/lib/python3.12/site-packages/unstructured/partition/pdf_image/pdfminer_processing.py", line 17, in <module>
    from unstructured.partition.pdf_image.pdfminer_utils import (
File "/home/user/Documents/ollama_pdf_rag/o_p_r/lib/python3.12/site-packages/unstructured/partition/pdf_image/pdfminer_utils.py", line 9, in <module>
    from pdfminer.psexceptions import PSSyntaxError

**Comment by mowtschan** [comment]
`pip install "unstructured[all-docs]"` - should fix it

**Comment by SecurityLover** [comment]
> `pip install "unstructured[all-docs]"` - should fix it

Thanks for your reply. 
I reinstalled it again with same `pip install "unstructured[all-docs]"`, and still the problem have not fixed. 
Any suggestion?
